### PR TITLE
[Content] Eldridge Kiefer Article

### PR DESCRIPTION
**Pull request by jdchart**
This will need to be reviewed by the musicians as it not only quotes them a lot, but also uses quite a bit of their material (audio, video, images).

### CODE REVIEW

**Comment by jdchart** [comment]
It's complaining about tags:

/learn/src/lib/layouts/madewithflucoma.svelte:4:12 Madewithflucoma has unused export property 'tags'. If it is for external reference only, please consider using `export const tags`

I'm assuming this has been changed quite recently (cause the article is using older format, flairs missing ect) and that I'll need to merge the main into it or sommit ?

**Comment by jdchart** [comment]
This can be merged and go live whenever !

**Comment by jamesb93** [comment]
Merge conflict, me sad. lets have a look

**Comment by jdchart** [comment]
Compress large assets, i'm assuming the video file was too big or something..?

**Comment by jdchart** [comment]
I get the feeling i caused you headaches... @jamesb93

**Comment by jamesb93** [comment]
> I get the feeling i caused you headaches... @jamesb93

not at all, all self inflictd in the name of progress. Tis the nature of collaborative and iterated work :)

**Pull request merged**
