### PR TITLE
[Enhance] Update reference page searchability

### PR DESCRIPTION
**Pull request by jamesb93**

### CODE REVIEW

**Comment by jamesb93** [comment]
@weefuzzy @jdchart 

I'm trying to work towards my first major goal of the learn platform: [Navigation and Discoverability](https://github.com/flucoma/learn-website/issues/91).

Would you be able to take a look at `/references` and see if this interface is a bit more digestable than its previous iteration?

**Comment by jdchart** [comment]
Format looks nicer than before (font + colours)
Much nicer that everything fits into one window, i can see everything at once.

Perhaps the blurb could appear in a popup when hovering on the name of the algorithm to give further explanation than just the algorithm name? But could clutter things.

**Comment by jamesb93** [comment]
> Format looks nicer than before (font + colours) Much nicer that everything fits into one window, i can see everything at once.
> 
> Perhaps the blurb could appear in a popup when hovering on the name of the algorithm to give further explanation than just the algorithm name? But could clutter things.

Its a nice idea but I think it will clutter things. Also doesn't work for screen readers which I'm trying to support as best I can.

**Comment by weefuzzy** [comment]
Agree it looks nicer. I miss what the search box could *potentially* have been (although I acknowledge that it wasn't that thing yet), but a vaguely intelligent way of filtering down that quite long list with some search terms would be really valuable. 

See the point about pop ups being difficult re clutter and screen readers, but I don't think this is insurmountable...

Anyway, in general I approve

**Comment by jamesb93** [comment]
I was wary of duplicating the search up the top. Maybe I can mix elements of the previous and current iteration though?

**Review by weefuzzy — APPROVED** [review]
I think we can return to the question of snazzy search fields later, in the interests of manageable PRs n' all that. This is definitely a stylistic and organisational improvement, which was the point ❤️

**Comment by jamesb93** [comment]
Cool, wangled it in for the impending PR storm.

**Pull request merged**
