### PR TITLE
[Content] SpectralShape Reference

### PR DESCRIPTION
**Pull request by jamesb93**
Adds a spectral shape reference to the learn platform.

### CODE REVIEW

**Comment by tedmoore** [comment]
@james, I was just looking at this guy and my widget was going nutz.

https://user-images.githubusercontent.com/1531144/152815790-deeae34b-023c-4352-b201-29fa7c6680e7.mov

**Comment by jamesb93** [comment]
> @james, I was just looking at this guy and my widget was going nutz.
> 
>  Screen.Recording.2022-02-07.at.10.13.47.mov

lol thats no good. I am still entirely unsure how best to make this interface. It all looks naff as hell to me :--(

**Comment by jamesb93** [comment]
Awaiting https://github.com/meyda/meyda/pull/1220 so I can do the crest then it should be done.

**Comment by tedmoore** [comment]
@james, I just checked this out again and my widget is still going nutz. I refreshed the page and then it stopped doing the glitchy thing but maybe it's still wonky.

**Comment by jamesb93** [comment]
> @james, I just checked this out again and my widget is still going nutz. I refreshed the page and then it stopped doing the glitchy thing but maybe it's still wonky.

Which browser?

**Comment by tedmoore** [comment]
> Which browser?

Chrome.

**Comment by jamesb93** [comment]
> > Which browser?
> 
> Chrome.

Can you retrieve the version for me?

**Comment by tedmoore** [comment]
> > > Which browser?
> > 
> > 
> > Chrome.
> 
> Can you retrieve the version for me?
Screenshot 2022-03-21 at 11 39 23

**Pull request merged**
