### PR TITLE
Content hayes

### PR DESCRIPTION
**Pull request by jdchart**

### CODE REVIEW

**Comment by jamesb93** [comment]
It is still not building for be72ecc because:

image

Keep at it!

**Comment by jdchart** [comment]
> It is still not building for [be72ecc](https://github.com/flucoma/learn-website/commit/be72ecc8de50ccd812a8f8cd279d409931b8447d) because:
> 
> image
> 
> Keep at it!

lol hoping this is it, where do you see those errors because when i run dev on my machine it doesnt throw anything up, on the netifly log?

**Comment by jamesb93** [comment]
I looked in the netlify log but on your machine you can run `npm run build` and it will try to build the site and then poop or succeed.

**Comment by jamesb93** [comment]
I reckon this is now ready to show to people.

**Comment by jdchart** [comment]
> I reckon this is now ready to show to people.

Indeedly!

Also realised that form the errors to show up on my local machine i needed to actually open the pages i the browser ! Thx 4 ur help!

**Pull request merged**
