### PR TITLE
[Enhancement] Various Learn Enhancements

### PR DESCRIPTION
**Pull request by jdchart**
This is going to be the PR that implements the general changes discussed in these issues: 

#199 
#200
#201 
#190 

Not ready to merge yet but will be soon.

### CODE REVIEW

**Comment by jdchart** [comment]
First, #201 , @tremblap I have simply added a link at the top of made-with directing towards a full catalogue of pieces made with the tools: https://learn-git-front-page-flucoma.vercel.app/madewithflucoma 

is this sufficient or do you want an entry under made-with?

And i suppose we must therefore remove the articles concerning the 2 gigs, even if i think it's a shame. I can link in the same manner, or again, make an article that directs people to all the different types of content on the www.

**Comment by jdchart** [comment]
Started working on a new homepage layout which i think will be better at showing what the site has to offer - although the implementation of it is a complete shit-show. Just prototyping ideas.

**Comment by jamesb93** [comment]
I would appreciate no one elses merges this till I have taken a look. Changing the names is more complicated than changing them on the surface of the HTML.

Also https://github.com/flucoma/learn-website/issues/190 is redundant now.

**Comment by jamesb93** [comment]
I've opened a new PR for #199 here https://github.com/flucoma/learn-website/pull/218

**Comment by jdchart** [comment]
Yep, will ping when need input, and good call to move #199 to #218 @jamesb93 . 

Indeed I was wanting to look at the front page stuff with you James, this was just to get an idea. Notably accessing the global layout css - I'd perhaps like things to be wider, less margin. And we can discuss how we would want to feature things - at the moment its just random on each page load. And perhaps talk about being able to define a featured image for each page so that there's potentially more eye-catching things on the front page. But i do like this layout where we can see more of everything at the same time (without it being chaotic).

**Comment by jdchart** [comment]
@tremblap for #201 , let me be more clear:

for the moment, I've just added a line of text and a link at the top of the made with flucoma page that points towards the www. learn catalogue of pieces.

is this sufficient, or do you want a full 'article' in the made with flucoma section that deals with this, and perhaps also other things that are on www like the gigs?

Also, there are two full entries in made with that deal with the gigs, but of course there's overlap with what's on the www website (even if I find the learn entries to be more complete). For the sake of not havign duplicates do you want me to remove these entries?

**Comment by jamesb93** [comment]
> Yep, will ping when need input, and good call to move #199 to #218 @jamesb93 .
> 
> Indeed I was wanting to look at the front page stuff with you James, this was just to get an idea. Notably accessing the global layout css - I'd perhaps like things to be wider, less margin. And we can discuss how we would want to feature things - at the moment its just random on each page load. And perhaps talk about being able to define a featured image for each page so that there's potentially more eye-catching things on the front page. But i do like this layout where we can see more of everything at the same time (without it being chaotic).

I agree with all of this :) Wider, pictures that get gobbled up as a preview. Let's talk about it more when you have some brainspace.

**Pull request closed without merging**
