### PR TITLE
Getting Started page

### PR DESCRIPTION
**Pull request by tedmoore**
This is what I had in mind for the "Getting Started" page. Not something that was prescriptive, but more curious about what the user is looking for. Hopefully a user can come to it and say _"There's the thing I want to do!"_.

What else do you all think should be on this page? What other kinds of _"Things"_, generally speaking, would someone want to do?

Also, I'm not too into how the page looks. Really it should look like our pretty, wide, picture filled `index.svx` pages, so I ping @jdchart and @jamesb93 if there are thoughts about that!?

Feel free to push on this branch. I'll be glad to see what you add!

### CODE REVIEW

**Comment by jamesb93** [comment]
I think the essential foundation of this is right (tutorials -> deeper articles). Some formatting would make it a little nicer, and I think it shouldn't necessarily conform to the article style. It could consume more of the page in the same way that the front page does.

**Comment by tedmoore** [comment]
> Some formatting would make it a little nicer, and I think it shouldn't necessarily conform to the article style.

@james I agree. This is outside my comfort zone with manipulating the svelte business.

**Comment by jamesb93** [comment]
> > Some formatting would make it a little nicer, and I think it shouldn't necessarily conform to the article style.
> 
> @james I agree. This is outside my comfort zone with manipulating the svelte business.

All goooood. I reckon me and Jacob can take this structure as a starting point and find a way to navigate it :)

**Comment by jdchart** [comment]
Hey! Sorry im a bit late to this party. I'll take a look now and see if there's some low hanging fruit!

**Review by tremblap — APPROVED** [review]
as discussed

**Comment by jdchart** [comment]
Ok just realised im pushing straight to this PR...

**Comment by jdchart** [comment]
my git game still leaves much to be desired

**Comment by jdchart** [comment]
ok working on the rest on a local branch... will get back to you !

**Pull request merged**
