### PR TITLE
[Content] LabelSet Reference

### PR DESCRIPTION
**Pull request by jamesb93**
Adds a labelset reference

### CODE REVIEW

**Review by tremblap — COMMENTED** [review]
This is great. One more caveat we had to explain 903842390482 times: identifiers and labels are strings, even if they are made only of digits, so 60 is in effect "60" and very often "60" != 60

**Comment by jamesb93** [comment]
yeah good catch. It is deffo important to explicate the types of the data under the hood.

**Comment by tedmoore** [comment]
> identifiers and labels are strings

Is it more accurate to say that they're "symbols" in SC this is an important distinction and I think in Max we use `[fromsymbol]` to convert to an int (for example), so tying in to that terminology might be good.

**Review by tedmoore — APPROVED** [review]
see comment above

**Pull request merged**
