### PR TITLE
KNNRegressor Reference

### PR DESCRIPTION
**Pull request by tedmoore**

### CODE REVIEW

**Comment by jamesb93** [comment]
is there a visualisation we could do here to help people understand what the KNNRegressor does? Happy to code something up if someone else can imagine it @tedmoore 🙊

**Comment by tedmoore** [comment]
I think the idea right now is to go light on this one until/if the multi-to-multi implementation get's done. At which point this can be fleshed out/changed to align with that functionality. That's my understanding from @tremblap.

**Review by tremblap — CHANGES_REQUESTED** [review]
that is a good place holder until I make it HD :) There is an ommission: the return is either a weighted or simple average between the K points, depending on the parameter weight (IIRC)

**Comment by tedmoore** [comment]
> that is a good place holder until I make it HD :) There is an ommission: the return is either a weighted or simple average between the K points, depending on the parameter weight (IIRC)

good catch!

**Pull request merged**
